// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/f-miyu/jinrou/server/app/data/repository"
	"github.com/f-miyu/jinrou/server/app/domain/service"
	"github.com/f-miyu/jinrou/server/app/infrastracture"
	"github.com/f-miyu/jinrou/server/app/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initializeJinrouServer(db *gorm.DB, tokenService service.TokenService) *infrastracture.JinrouServer {
	gameRepository := repository.NewGameRepository()
	userRepository := repository.NewUserRepository(db)
	gameUsecase := usecase.NewGameUsecase(gameRepository, userRepository)
	refreshTokenRepository := repository.NewRefreshTokenRepository(db)
	authUsecase := usecase.NewAuthUsecase(tokenService, refreshTokenRepository, userRepository)
	jinrouServer := infrastracture.NewJinrouServer(gameUsecase, authUsecase)
	return jinrouServer
}
